name: nwp
channels:
  - conda-forge
dependencies:
  - python>=3.9

  # Scientific Python
  - zarr
  - xarray
  - cfgrib

  # Development tools
  - pytest
  - flake8
  - jedi
  - mypy
  - black
  - pre-commit

  # pip
  - pip:
    - ocf_blosc2
